<?php
    $x = $_GET['estado'];

    switch($x){
        case "SP";
        echo "<h1>São Paulo</h1>";
        break;
        case "SC";
        echo "<h1>Florianópolis</h1>";
        break;
        case "MG";
        echo "<h1>Belo Horizonte</h1>";
        break;
        case "PR";
        echo "<h1>Curitiba</h1>";
        break;
        case "RS";
        echo "<h1>Porto Alegre</h1>";
        break;
        case "ES";
        echo "<h1>Vitória</h1>";
        break;
        case "PA";
        echo "<h1>Belém</h1>";
        break;
        case "RN";
        echo "<h1>Natal</h1>";
        break;
        case "PE";
        echo "<h1>Recife</h1>";
        break;
        case "MG";
        echo "<h1>Cuiabá</h1>";
        break;
        case "MA";
        echo "<h1>São Luís</h1>";
        break;
        case "RR";
        echo "<h1>Boa Vista</h1>";
        break;
        case "MS";
        echo "<h1>Campo Grande</h1>";
        break;
        case "PB";
        echo "<h1>João Pessoa</h1>";
        break;
        case "AL";
        echo "<h1>Maceió</h1>";
        break;
        case "SE";
        echo "<h1>Aracaju</h1>";
        break;
        case "RO";
        echo "<h1>Porto Velho</h1>";
        break;
        case "PI";
        echo "<h1>Teresina</h1>";
        break;
        case "TO";
        echo "<h1>Palmas</h1>";
        break;
        case "AM";
        echo "<h1>Manaus</h1>";
        break;
        case "BA";
        echo "<h1>Salvador</h1>";
        break;
        case "AM";
        echo "<h1>Macapá</h1>";
        break;
        case "CE";
        echo "<h1>Fortaleza</h1>";
        break;
        case "AC";
        echo "<h1>Rio Branco</h1>";
        break;
        case "GO";
        echo "<h1>Goiânia</h1>";
        break;
        case "RJ";
        echo "<h1>Rio de Janeiro</h1>";
        break;
    }
?>
<a href='form.html'><button>Voltar</button></a>
